{
 "title": "TimeMap GeoMap",
 "description": "GeoMap-Infinity-Plugin",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 22, "x": 0, "y": 0 },
   "options": {
    "content": "<center>\n  <br>\n  <h1>TimeMap</h1>\n  <p>\n    Click on a node on the TimeMap Sampling panel to access the detailed view about the sampled lantecy and jitter measurements.\n  </p>\n  <br>\n</center>\n\n"
   }
  },
  {
   "title": " topology",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "parser": "backend",
     "root_selector": "$map(elements.nodes[data.client=\"${__org.name}\" or data.id=\"pedraforca\" or data.id=\"lapica\"], function($v){{\n          \"id\": $v.data.id,\n          \"name\": $v.data.name,\n          \"flavor\": $v.data.flavor,\n          \"latitude\": $v.data.latitude,\n          \"longitude\": $v.data.longitude,\n          \"client\": $v.data.client,\n          \"client code\": $v.data.code_client\n}})",
     "source": "url",
     "type": "json",
     "url": "http://172.17.0.1/tm/latest_graph.json",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "parser": "backend",
     "root_selector": "elements.edges[data.client=\"${__org.name}\"].data",
     "source": "url",
     "type": "json",
     "url": "http://172.17.0.1/tm/latest_graph.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "TimeMap Sampling (based on Twamp)",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 14, "x": 8, "y": 4 },
   "targets": [
    {
     "query": "// Obtenemos posiciones desde los campos de origen\r\nsrc_nodes = from(bucket: v.defaultBucket)\r\n  |> range(start: -10m)\r\n  |> filter(fn: (r) => r._measurement == \"exec_snmp\")\r\n  |> filter(fn: (r) => r._field == \"src_latitude\" or r._field == \"src_longitude\")\r\n  |> last()\r\n  |> pivot(rowKey: [\"src_short\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ id: r.src_short, latitude: float(v: r.src_latitude), longitude: float(v: r.src_longitude) }))\r\n\r\n// Obtenemos posiciones desde los campos de destino\r\ndst_nodes = from(bucket: v.defaultBucket)\r\n  |> range(start: -10m)\r\n  |> filter(fn: (r) => r._measurement == \"exec_snmp\")\r\n  |> filter(fn: (r) => r._field == \"dst_latitude\" or r._field == \"dst_longitude\")\r\n  |> last()\r\n  |> pivot(rowKey: [\"dst_short\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ id: r.dst_short, latitude: float(v: r.dst_latitude), longitude: float(v: r.dst_longitude) }))\r\n\r\n// Unimos todo en una sola lista de nodos únicos\r\nunion(tables: [src_nodes, dst_nodes])\r\n  |> group(columns: [\"id\"])\r\n  |> last(column: \"latitude\")\r\n  |> group()"
    },
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start:-10m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"exec_snmp\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"posRttJitterMax\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> group()\r\n  |> keep(columns: [\"_time\", \"dst_short\", \"src_short\", \"_value\"])\r\n  |> rename(columns: {_value:\"posRttJitterMax\", dst_short:\"target\", src_short:\"source\"})\r\n  |> group(columns:[\"source\",\"target\"])\r\n  |> last(column: \"_time\")\r\n  |> group()"
    }
   ]
  },
  { "title": "Raw data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": " nodes",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 19 },
   "targets": [
    {
     "parser": "backend",
     "root_selector": "$map(elements.nodes[data.client=\"${__org.name}\" or data.id=\"pedraforca\" or data.id=\"lapica\"], function($v){{\n          \"id\": $v.data.id,\n          \"name\": $v.data.name,\n          \"flavor\": $v.data.flavor,\n          \"latitude\": $v.data.latitude,\n          \"longitude\": $v.data.longitude,\n          \"client\": $v.data.client,\n          \"client code\": $v.data.code_client\n}})",
     "source": "url",
     "type": "json",
     "url": "http://172.17.0.1/tm/latest_graph.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": " Edges ",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 19 },
   "targets": [
    {
     "parser": "backend",
     "root_selector": "elements.edges[data.client=\"${__org.name}\"].data",
     "source": "url",
     "type": "json",
     "url": "http://172.17.0.1/tm/latest_graph.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "TimeMap probes - Nodes",
   "type": "table",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 26 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: -10m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"exec_snmp\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sample_is_valid\" or r[\"_field\"] == \"src_latitude\" or r[\"_field\"] == \"src_longitude\" or r[\"_field\"] == \"flavor\")\r\n  |> group(columns: [\"src_short\", \"flavor\"])\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> last(column: \"_time\")\r\n  |> keep(columns: [\"_time\",\"src_longitude\",\"src_latitude\", \"sample_is_valid\",\"src_short\", \"flavor\"])\r\n  |> group()\r\n  |> rename(columns: {src_short:\"id\", src_latitude:\"latitude\", src_longitude:\"longitude\", sample_is_valid:\"_value\"})"
    }
   ]
  },
  {
   "title": "TimeMap probes - Edges",
   "type": "table",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 26 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start:-10m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"exec_snmp\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"posRttJitterMax\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> group()\r\n  |> keep(columns: [\"_time\", \"dst_short\", \"src_short\", \"_value\"])\r\n  |> rename(columns: {_value:\"posRttJitterMax\", dst_short:\"target\", src_short:\"source\"})\r\n  |> group(columns:[\"source\",\"target\"])\r\n  |> last(column: \"_time\")\r\n  |> group()"
    }
   ]
  },
  {
   "title": "TimeMap probes - Edges",
   "type": "table",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start:-10m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"exec_snmp\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sample_is_valid\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> group()\r\n  |> keep(columns: [\"_time\", \"dst_short\", \"src_short\", \"_value\"])\r\n  |> rename(columns: {_value:\"sample_is_valid\", dst_short:\"target\", src_short:\"source\"})\r\n  |> group(columns:[\"source\",\"target\"])\r\n  |> last(column: \"_time\")\r\n  |> group()"
    }
   ]
  }
 ]
}