{
 "title": "Timemap - Latency / Jitter Details",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "src",
    "label": "Source",
    "query": {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: -120m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"exec_rpm\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sample_is_valid\" or r[\"_field\"] == \"src_latitude\" or r[\"_field\"] == \"src_longitude\")\r\n  |> group(columns: [\"src_short\"])\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> last(column: \"_time\")\r\n  |> keep(columns: [\"src_short\"])\r\n  |> group()\r\n"
    }
   },
   {
    "name": "dst",
    "label": "Destination",
    "query": {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: -120m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"exec_rpm\")\n  |> filter(fn: (r) => r[\"_field\"] == \"sample_is_valid\" or r[\"_field\"] == \"dst_latitude\" or r[\"_field\"] == \"dst_longitude\")\n  |> group(columns: [\"dst_short\"])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> last(column: \"_time\")\n  |> keep(columns: [\"dst_short\"])\n  |> group()\n"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RTT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> drop(columns: [\"host\", \"src_ip\", \"dst_ip\", \"dst\", \"src\"])  \r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"exec_rpm\" and r.src_short == \"${src}\" and r.dst_short == \"${dst}\" \r\n  )\r\n  |> filter(fn: (r) => r[\"_field\"] == \"roundTripTimeMin\" or r[\"_field\"] == \"roundTripTimeAverage\" or r[\"_field\"] == \"roundTripTimeMax\"\r\n  )\r\n\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"anomaly_twamp\" and r.original_metric == \"roundTripTimeMax\" and r[\"dst\"] =~ /${dst}/ and r.src =~ /${src}/ )\r\n  |> filter(fn: (r) => r[\"_field\"] == \"twamp_Anomaly\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RTT Deviation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> drop(columns: [\"host\", \"src_ip\", \"dst_ip\", \"src\", \"dst\"])  \r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"exec_rpm\" and r.src_short == \"${src}\" and r.dst_short == \"${dst}\" \r\n  )\r\n  |> filter(fn: (r) => r[\"_field\"] == \"roundTripTimeStdDev\" \r\n  )\r\n\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Jitter (RTT Positive/Negative)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> drop(columns: [\"host\", \"src_ip\", \"dst_ip\", \"dst\", \"src\"])  \r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"exec_rpm\" and r.src_short == \"${src}\" and r.dst_short == \"${dst}\" \r\n  )\r\n  |> filter(fn: (r) => r[\"_field\"] == \"posRttJitterMin\" or r[\"_field\"] == \"posRttJitterMax\" or r[\"_field\"] == \"posRttJitterAverage\"\r\n  )\r\n\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> drop(columns: [\"host\", \"src_ip\", \"dst_ip\", \"dst\", \"src\"])  \r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"exec_rpm\" and r.src_short == \"${src}\" and r.dst_short == \"${dst}\" \r\n  )\r\n  |> filter(fn: (r) => r[\"_field\"] == \"negRttJitterMin\" or r[\"_field\"] == \"negRttJitterMax\" or r[\"_field\"] == \"negRttJitterAverage\"\r\n  )\r\n  |> map(fn: (r) => ({ r with _value: r._value * -1.0  }))\r\n\r\n\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"anomaly_twamp\" and r.dst == \"${dst}\" and r.src == \"${src}\" and r.original_metric == \"posRttJitterMax\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"twamp_Anomaly\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Jitter Deviations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> drop(columns: [\"host\", \"src_ip\", \"dst_ip\", \"dst\", \"src\"])  \r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"exec_rpm\" and r.src_short == \"${src}\" and r.dst_short == \"${dst}\" \r\n  )\r\n  |> filter(fn: (r) => r[\"_field\"] == \"posRttJitterStdDev\" or r[\"_field\"] == \"negRttJitterStdDev\"\r\n  )\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      _value: if r._field == \"negRttJitterStdDev\" then float(v: r._value) * -1.0 else float(v: r._value)\r\n  }))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ingress / Egress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> drop(columns: [\"host\", \"src_ip\", \"dst_ip\", \"dst\", \"src\"])  \r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"exec_rpm\" and r.src_short == \"${src}\" and r.dst_short == \"${dst}\" \r\n  )\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ingressMin\" or r[\"_field\"] == \"ingressMax\" or r[\"_field\"] == \"ingressAverage\"\r\n  )\r\n\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> drop(columns: [\"host\", \"src_ip\", \"dst_ip\", \"dst\", \"src\"])  \r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"exec_rpm\" and r.src_short == \"${src}\" and r.dst_short == \"${dst}\" \r\n  )\r\n  |> filter(fn: (r) => r[\"_field\"] == \"egressMin\" or r[\"_field\"] == \"egressMax\" or r[\"_field\"] == \"egressAverage\"\r\n  )\r\n  |> map(fn: (r) => ({ r with _value: r._value * -1.0  }))\r\n\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ingress / Egress Deviations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> drop(columns: [\"host\", \"src_ip\", \"dst_ip\", \"dst\", \"src\"])  \r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"exec_rpm\" and r.src_short == \"${src}\" and r.dst_short == \"${dst}\" \r\n  )\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ingressStdDev\")\r\n\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> drop(columns: [\"host\", \"src_ip\", \"dst_ip\", \"dst\", \"src\"])  \r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"exec_rpm\" and r.src_short == \"${src}\" and r.dst_short == \"${dst}\" \r\n  )\r\n  |> filter(fn: (r) => r[\"_field\"] == \"egressStdDev\"\r\n  )\r\n  |> map(fn: (r) => ({ r with _value: r._value * -1.0  }))\r\n\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}