{
 "title": "TimeMap Node",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "src",
    "label": "Router",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(bucket: v.defaultBucket, tag: \"src_short\")"
    }
   },
   {
    "name": "outgoing",
    "query": "from(bucket: v.defaultBucket) |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r[\"_measurement\"] == \"exec_rpm\") |> filter(fn: (r) => r[\"src_short\"] == \"${src}\") |> keep(columns:[\"dst_short\"]) |> unique(column: \"dst_short\")"
   },
   {
    "name": "outgoing",
    "query": {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"exec_rpm\")\r\n  |> group(columns: [\"src_short\", \"dst_short\"])\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> last(column:\"_time\")\r\n  |> group()\r\n  |> drop(columns:[\"dst_latitude\",\"dst_longitude\",\"src_latitude\",\"src_longitude\",\"_start\",\"_stop\"])\r\n  |> filter(fn: (r) => r[\"src_short\"] == \"${src}\"  )\r\n  |> keep(columns:[\"dst_short\"])"
    }
   },
   {
    "name": "incoming",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"exec_rpm\")\r\n  |> group(columns: [\"src_short\", \"dst_short\"])\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> last(column:\"_time\")\r\n  |> group()\r\n  |> drop(columns:[\"dst_latitude\",\"dst_longitude\",\"src_latitude\",\"src_longitude\",\"_start\",\"_stop\"])\r\n  |> filter(fn: (r) => r[\"dst_short\"] == \"${src}\" )\r\n  |> keep(columns:[\"src_short\"])"
   }
  ]
 },
 "panels": [
  {
   "title": "Device family",
   "type": "stat",
   "gridPos": { "h": 3, "w": 22, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: -10m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"exec_rpm\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sample_is_valid\" or r[\"_field\"] == \"flavor\")\r\n  |> filter(fn: (r)=> r.src_short == \"${src}\")\r\n  |> last(column: \"_time\")\r\n  |> group()\r\n\r\n"
    }
   ]
  },
  { "title": "Latest raw samples", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "datagrid",
   "type": "table",
   "description": "Last sampled points\n",
   "gridPos": { "h": 16, "w": 22, "x": 0, "y": 4 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"exec_rpm\")\n  |> group(columns: [\"src_short\", \"dst_short\"])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> last(column:\"_time\")\n  |> group()\n  |> drop(columns:[\"dst_latitude\",\"dst_longitude\",\"src_latitude\",\"src_longitude\",\"_start\",\"_stop\"])\n  |> filter(fn: (r) => r[\"src_short\"] == \"${src}\" or r[\"dst_short\"] == \"${src}\" )"
    }
   ]
  },
  { "title": "TimeMap Node Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Node ${src} quick status",
   "type": "nodeGraph",
   "gridPos": { "h": 15, "w": 22, "x": 0, "y": 21 },
   "targets": [
    {
     "query": "d=from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"exec_rpm\")\r\n  |> aggregateWindow(every: 1h, fn: last, createEmpty: false)\r\n  |> group(columns: [\"src_short\", \"dst_short\"])\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> last(column:\"_time\")\r\n  |> group()\r\n  |> drop(columns:[\"dst_latitude\",\"dst_longitude\",\"src_latitude\",\"src_longitude\"])\r\n  |> filter(fn: (r) => r[\"src_short\"] == \"${src}\" or r[\"dst_short\"] == \"${src}\" )\r\n\r\nd_src = d\r\n  |>keep(columns:[\"src_short\",\"sample_is_valid\"])\r\n  |>rename(columns: {src_short: \"id\", sample_is_valid: \"arc__valid\"})\r\n  |> filter(fn: (r) => exists r[\"id\"] )\r\n\r\nd_dst = d\r\n  |>keep(columns:[\"dst_short\",\"sample_is_valid\"])\r\n  |>rename(columns: {dst_short: \"id\", sample_is_valid: \"arc__valid\"})\r\n  |> filter(fn: (r) => exists r[\"id\"] )\r\n\r\nunion(tables: [d_src, d_dst]) \r\n  |> duplicate(as: \"title\", column: \"id\")\r\n  |> unique(column:\"id\")\r\n  |> map(fn: (r) => ({ r with mainstat: if r[\"arc__valid\"] > 0 then \"Status OK\" else \"No Data\"  }))\r\n"
    },
    {
     "query": "d=from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"exec_rpm\")\r\n  |> aggregateWindow(every: 1h, fn: last, createEmpty: false)\r\n  |> group(columns: [\"src_short\", \"dst_short\"])\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> last(column:\"_time\")\r\n  |> group()\r\n  |> drop(columns:[\"dst_latitude\",\"dst_longitude\",\"src_latitude\",\"src_longitude\"])\r\n  |> filter(fn: (r) => r[\"src_short\"] == \"${src}\" or r[\"dst_short\"] == \"${src}\" )\r\n  |> rename(columns: {src_short: \"source\", dst_short: \"target\"})\r\n  |> map(fn: (r) => ({ r with id: string(v: r[\"source\"]+\"--\"+r[\"target\"]) }))\r\n  |> filter(fn: (r) => exists r[\"id\"] )\r\n\r\n\r\nd \r\n  |> map(fn: (r) => ({ r with mainstat: \"Jitter: \" + string(v: r[\"posRttJitterMax\"]) + \"ms\" }))\r\n  |> map(fn: (r) => ({ r with secondarystat: \"RTT: \" + string(v: r[\"roundTripTimeMax\"]) +\"ms\" }))\r\n\r\n"
    }
   ]
  },
  {
   "title": "Outgoing link  from ${src}  to ${outgoing}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "repeat": "outgoing"
  },
  {
   "title": "RTT",
   "type": "timeseries",
   "description": " r.dst_short == \"${incoming}\" and r.src_short == \"${src}\"",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "\r\nfrom(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> drop(columns: [\"host\", \"src_ip\", \"dst_ip\", \"dst\", \"src\"])  \r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"exec_rpm\" and r.src_short == \"${src}\" and r.dst_short == \"${outgoing}\" \r\n  )\r\n  |> filter(fn: (r) => r[\"_field\"] == \"roundTripTimeMin\" or r[\"_field\"] == \"roundTripTimeAverage\" or r[\"_field\"] == \"roundTripTimeMax\"\r\n  )\r\n\r\n\r\n"
    },
    {
     "query": "import \"join\"\r\nimport \"math\"\r\n\r\nd = from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> drop(columns: [\"host\", \"src_ip\", \"dst_ip\", \"dst\", \"src\"])  \r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"exec_rpm\" and r.src_short == \"${src}\" and r.dst_short == \"${outgoing}\" \r\n  )\r\n  |> filter(fn: (r) => r[\"_field\"] == \"roundTripTimeMin\" or r[\"_field\"] == \"roundTripTimeAverage\" or r[\"_field\"] == \"roundTripTimeMax\"\r\n  )\r\n\r\n\r\n\r\nmad = (table=<-, threshold=1.0) => {\r\n    med = table |> group()\r\n      |> group(columns: [\"_field\"]) \r\n      |> median(column: \"_value\")\r\n      |> group()\r\n    d_with_diff = join.inner(\r\n            left: table |> group(),\r\n            right: med,\r\n            on: (l, r) => l._field==r._field,\r\n            as: (l, r) => ({l with med: r._value, diff: math.abs(x: l._value - r._value) }),\r\n        )\r\n    norm_mad = d_with_diff \r\n      |> group(columns: [\"_field\"])\r\n      |> median(column: \"diff\")\r\n      |> map(fn: (r) => ({ r with mad: 1.4826*r.diff}))\r\n      |> group()\r\n      |> drop(columns: [\"diff\"])\r\n\r\n    return join.inner(\r\n            left: d_with_diff,\r\n            right: norm_mad,\r\n            on: (l, r) => l._field==r._field,\r\n            as: (l, r) => ({l with score: if r.mad > 0.0 then l.diff/r.mad else 0.0}),\r\n        )\r\n        |> map(fn: (r) => ({ r with anomaly: if r.score > threshold then 1 else 0 }))\r\n}\r\n\r\nd |> mad(threshold:6)\r\n  |> filter(fn: (r) => r.anomaly >0 )\r\n  |> keep(columns: [\"_time\",\"_field\",\"_value\"])\r\n  |> rename(columns: {_value: \"Anomaly\"})\r\n  |> group(columns: [\"_field\"])\r\n  \r\n"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "timeseries",
   "description": " r.dst_short == \"${incoming}\" and r.src_short == \"${src}\"",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> drop(columns: [\"host\", \"src_ip\", \"dst_ip\", \"dst\", \"src\"])  \r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"exec_rpm\" and r.src_short == \"${src}\" and r.dst_short == \"${outgoing}\" \r\n  )\r\n  |> filter(fn: (r) => r[\"_field\"] == \"posRttJitterMin\" or r[\"_field\"] == \"posRttJitterMax\" or r[\"_field\"] == \"posRttJitterAverage\"\r\n  )\r\n\r\n"
    },
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> drop(columns: [\"host\", \"src_ip\", \"dst_ip\", \"dst\", \"src\"])  \r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"exec_rpm\" and r.src_short == \"${src}\" and r.dst_short == \"${outgoing}\" \r\n  )\r\n  |> filter(fn: (r) => r[\"_field\"] == \"negRttJitterMin\" or r[\"_field\"] == \"negRttJitterMax\" or r[\"_field\"] == \"negRttJitterAverage\"\r\n  )\r\n  |> map(fn: (r) => ({ r with _value: r._value * -1.0  }))\r\n\r\n\r\n"
    },
    {
     "query": "import \"join\"\r\nimport \"math\"\r\n\r\nd = from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> drop(columns: [\"host\", \"src_ip\", \"dst_ip\", \"dst\", \"src\"])  \r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"exec_rpm\" and r.src_short == \"${src}\" and r.dst_short == \"${outgoing}\" \r\n  )\r\n  |> filter(fn: (r) => r[\"_field\"] == \"posRttJitterMin\" or r[\"_field\"] == \"posRttJitterMax\" or r[\"_field\"] == \"posRttJitterAverage\"\r\n    or  r[\"_field\"] == \"negRttJitterMin\" or r[\"_field\"] == \"negRttJitterMax\" or r[\"_field\"] == \"negRttJitterAverage\"\r\n  )\r\n\r\n\r\nmad = (table=<-, threshold=1.0) => {\r\n    med = table |> group()\r\n      |> group(columns: [\"_field\"]) \r\n      |> median(column: \"_value\")\r\n      |> group()\r\n    d_with_diff = join.inner(\r\n            left: table |> group(),\r\n            right: med,\r\n            on: (l, r) => l._field==r._field,\r\n            as: (l, r) => ({l with med: r._value, diff: math.abs(x: l._value - r._value) }),\r\n        )\r\n    norm_mad = d_with_diff \r\n      |> group(columns: [\"_field\"])\r\n      |> median(column: \"diff\")\r\n      |> map(fn: (r) => ({ r with mad: 1.4826*r.diff}))\r\n      |> group()\r\n      |> drop(columns: [\"diff\"])\r\n\r\n    return join.inner(\r\n            left: d_with_diff,\r\n            right: norm_mad,\r\n            on: (l, r) => l._field==r._field,\r\n            as: (l, r) => ({l with score: if r.mad > 0.0 then l.diff/r.mad else 0.0}),\r\n        )\r\n        |> map(fn: (r) => ({ r with anomaly: if r.score > threshold then 1 else 0 }))\r\n}\r\n\r\nd |> mad(threshold:6)\r\n  |> filter(fn: (r) => r.anomaly >0 )\r\n  |> map(fn: (r) => ({ r with _value: if r[\"_field\"] == \"negRttJitterMin\" or r[\"_field\"] == \"negRttJitterMax\" or r[\"_field\"] == \"negRttJitterAverage\" then -1.0*r._value else r._value }))\r\n  |> keep(columns: [\"_time\",\"_field\",\"_value\"])\r\n  |> rename(columns: {_value: \"Anomaly\"})\r\n  |> group(columns: [\"_field\"])"
    }
   ]
  },
  {
   "title": "Get more details",
   "type": "stat",
   "gridPos": { "h": 3, "w": 22, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"exec_rpm\")\r\n  |> group(columns: [\"src_short\", \"dst_short\"])\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> last(column:\"_time\")\r\n  |> group()\r\n  |> drop(columns:[\"dst_latitude\",\"dst_longitude\",\"src_latitude\",\"src_longitude\",\"_start\",\"_stop\"])\r\n  |> filter(fn: (r) => r[\"dst_short\"] == \"${outgoing}\" )\r\n  |> keep(columns:[\"dst_short\"])\r\n  |> unique(column:\"dst_short\")\r\n  |> map(fn: (r) => ({ r with datalink: \"${src}-->\"+r[\"dst_short\"] }))\r\n\r\n  "
    }
   ]
  }
 ]
}